portfolio_django/portfolio/home/urls.py
from django.urls import path

from .views import (IndexTemplateView, ProjetoCreateView,
                    ProjetoDetailTemplateView)

app_name = 'home'

urlpatterns = [

    # Get HOME PAGE -> /
    path(
        '',
        IndexTemplateView.as_view(),
        name ='index'
    ),

    ## Utilizando o ID para buscar o projeto
    path(
        'video/projeto/<pk>',
        ProjetoDetailTemplateView.as_view(),
        name = 'projetos_detail'
    ),

    ## Criar um novo projeto
    path(
        'projeto/new/',
        ProjetoCreateView.as_view(),
        name = 'adicionar_projeto'
    ),
]

portfolio_django/portfolio/portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    ## Home Page
    path("", include("home.urls", namespace="home")),
    ## Interface Admin
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = "home.views.handle_bad_request"
handler403 = "home.views.handle_permission_denied"
handler404 = "home.views.handle_not_found"
handler500 = "home.views.handle_server_error"

portfolio_django/portfolio/portfolio/models.py
import os

from django.db import models

from .settings import MEDIA_ROOT

"""
TITULO
PRINT(HOME) - capa - img do projeto
VIDEO
LINK DO CÓDIGO NO GIT HUB
"""

class Projeto(models.Model):

	titulo = models.CharField(
		max_length = 100,
		null = False,
		blank = False,
		unique = True,
	)
	
	capa = models.ImageField(
		upload_to= '',
		max_length=None,
		blank=False,
		unique=True,
		null=False,
	)
	
	@property
	def capa_path(self):
		if self.capa and hasattr(self.capa, 'url'):
			return self.capa.url
	
	iframe_video = models.TextField(
		unique=True,
		null = False,
		blank = False,
	)
	
	link_codigo = models.URLField(
		unique = True,
		null = False,
		blank = False,
		default = 'https://github.com/clcosta/'
	)

	objetos = models.Manager()

portfolio_django/portfolio/home/forms.py
from django import forms
from portfolio.models import Projeto


class ProjetoCreateForm(forms.ModelForm):
    
    titulo = forms.CharField(
        label="Titulo do Projeto",
		max_length = 100,
        required=True,
        min_length=5,
	)

    capa = forms.FileField(
        label= "Selecione uma imagem para a Capa do Projeto",
        allow_empty_file=False,
        required=True,
    )

    link_codigo = forms.URLField(
        label= "link do Código no GitHub ",
        required=True,
    )

    iframe_video = forms.CharField(
        label = "Iframe (Vídeo) que será exibido na página! ",
        max_length=1000,
        widget=forms.widgets.Textarea,
    )

    class Meta:
        model = Projeto
        fields = '__all__'

portfolio_django/portfolio/home/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from portfolio.models import Projeto

from home.forms import ProjetoCreateForm


class IndexTemplateView(ListView):
    template_name = "home/index.html"
    model = Projeto
    fields = [
        'id',
        'titulo',
        'capa',
    ]
    context_object_name = "projetos"

class ProjetoDetailTemplateView(DetailView):
    template_name = 'home/projeto.html'
    model = Projeto
    fields = [
        'titulo',
        'iframe_video',
        'link_codigo',
    ]
    context_object_name = "projetos_detail"

class ProjetoCreateView(CreateView):
    template_name = 'home/adicionar_projeto.html'
    model = Projeto
    form_class = ProjetoCreateForm
    success_url = reverse_lazy(
        "home:index"
    )

def handle_not_found(request, exception):
    return render(request, '404.html')

def handle_server_error(request):
    return render(request, '500.html')

def handle_permission_denied(request, exception):
    return render(request, '403.html')

def handle_bad_request(request, exception):
    return render(request, '400.html')

portfolio_django/portfolio/home/templates/home/adicionar_projeto.html
{% load crispy_forms_tags %}


<!-- BOOTSTRAP -->

<body style="background-color: #afaeae;">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Title -->
        <title>Claudio Lima - Adicionar Projeto</title>
        {% load static %}
        <link rel="shortcut icon" href="{% static '/home/img/icon.ico' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Lato&family=Roboto&display=swap"
            rel="stylesheet">
        <script src="https://kit.fontawesome.com/f0e17cbf2f.js" crossorigin="anonymous"></script>
    </head>
    <!-- NAVBAR BOOTSRAP -->
    <nav class="navbar navbar-expand mb-3" style="background-color: #000200;">
        <div class="container">
            <a class="navbar-brand" href="#" style="color: #00dbd0;">Projetos Manager</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}" style="color: #49b889;">Página inicial</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="#" style="color: #49b889;">Como utilizar</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if user.is_superuser %}
    <!-- FORMULARIO -->
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </form>
    </div>
    {% else %}
    <div class="container text-center" style="margin-top: 40px;">
        <img src="{% static '/home/img/logo.png' %}" alt="">
    </div>
    <div class="container" style="margin-top: 90px;">
        <h1 class="text-center" style="text-align: center;font-size: 116px;font-family:'Bebas Neue', sans-serif;color: #FFFFFF;">Você não é
            um Administrador!</h1>
    </div>
    {% endif %}
</body>

portfolio_django/portfolio/home/templates/home/index.html
{% extends 'home/home_base.html' %}

{% load static %}

{% block list_projects %}

{% for projeto in projetos %}
<div class="list-item py-6" id="projeto-{{ projeto.id }}">
    {% if projeto.id < 10 %}
    <h5 class="color-gray mr-2"><id>0{{ projeto.id }}.</h5>
        {% else %}
        <h5 class="color-gray mr-2"><id>{{ projeto.id }}.</h5>
            {% endif %}
            <a href= "{% url 'home:projetos_detail' projeto.id %}" target="_blank" class="link-projeto">
                <h3>{{ projeto.titulo }}</h3>
            </a>
            <img src="{{ projeto.capa_path }}"class="img-project" alt="">
        </div>
    {% endfor %}
{% endblock %}

portfolio_django/portfolio/home/templates/home/projeto.html
{% extends 'home/projetos_base.html' %}

{% load static %}

{% block title_video %}{{ projetos_detail.titulo }}{% endblock %}

{% block video %}
    {% autoescape off %}
    {{ projetos_detail.iframe_video }}
    {% endautoescape %}
{% endblock %}

{% block codigo %}
<div class="text-center"><a href="{{ projetos_detail.link_codigo }}" class="git" target="_blank" id="git-button">Ir para GitHub</a></div>
{% endblock %}

portfolio_django/portfolio/templates/base_error.html
<!DOCTYPE html>
<html lang="pt-br">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{%block title%}{% endblock %}</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link rel="shortcut icon" href="{% static '/home/img/icon.ico' %}">
    <link rel= "stylesheet" type= "text/css" href="{% static '/home/css/style.css' %}">

    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>


</head>
<body>
    <!-- HEADER -->
    <header class="menu">
        <div class="menu-left">
        </div>
        <div class="menu-logo">
            <img src="{% static '/home/img/logo.png' %}" style="width: 80%;padding-left: 15px;" alt="">
        </div>
        <div class="menu-right">
        </div>
    </header>
    <!-- Background -->
    <div class="relative">
        <div class="bg-hero">
            <svg viewBox="0 0 2058 1099" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g id="Cover">
                <rect id="block-3" x="394" y="423.728" width="18" height="18" transform="rotate(-45 394 423.728)" fill="url(#paint0_linear)"/>
                <rect id="block-2" x="1732" y="411.728" width="18" height="18" transform="rotate(-45 1732 411.728)" fill="url(#paint1_linear)"/>
                <rect id="block-1" x="1038" y="693.556" width="22" height="22" transform="rotate(-45 1038 693.556)" fill="url(#paint2_linear)"/>
                <g id="linha-cima">
                <g id="linha 1" opacity="0.7" filter="url(#filter0_f)">
                <path d="M892.758 205.575C1073.31 178.617 1291.91 214.514 1431.3 275.21" stroke="url(#paint3_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                <g id="linha 2" opacity="0.7" filter="url(#filter1_f)">
                <path d="M947.199 198.29C828.671 217.473 785.221 196.311 735.351 134.878" stroke="url(#paint4_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                </g>
                <g id="linha-meio">
                <g id="Group 5">
                <g id="linha 1_2" opacity="0.7" filter="url(#filter2_f)">
                <path d="M884.276 994.467C812.584 1039.61 710.222 1026.84 636.372 981.508" stroke="url(#paint5_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                <g id="linha 2_2" opacity="0.7" filter="url(#filter3_f)">
                <path d="M862.47 1007.25C909.199 976.149 932.728 992.487 968.164 1047.78" stroke="url(#paint6_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                </g>
                </g>
                <g id="linha-esquer">
                <g id="linha 1_3" opacity="0.7" filter="url(#filter4_f)">
                <path d="M93.6238 782.989C186.823 742.936 299.827 793.325 371.968 880" stroke="url(#paint7_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                <g id="linha 2_3" opacity="0.7" filter="url(#filter5_f)">
                <path d="M121.728 772.129C60.5468 800.567 38.0544 770.314 12.1529 682" stroke="url(#paint8_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                </g>
                <g id="linha-direita">
                <g id="linha 1_4" opacity="0.7" filter="url(#filter6_f)">
                <path d="M1889.59 995.524C1762.77 1093.3 1569.42 1115.92 1424.18 1077.53" stroke="url(#paint9_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                <g id="linha 2_4" opacity="0.7" filter="url(#filter7_f)">
                <path d="M1850.87 1023.82C1933.26 957.556 1979.84 972.657 2054.86 1041.88" stroke="url(#paint10_radial)" stroke-opacity="0.8" stroke-width="3"/>
                </g>
                </g>
                </g>
                <defs>
                <filter id="filter0_f" x="890.67" y="192.996" width="543.347" height="85.5867" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter1_f" x="731.91" y="131.897" width="217.494" height="76.5927" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter2_f" x="633.583" y="978.226" width="253.483" height="47.8727" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter3_f" x="859.671" y="988.141" width="111.761" height="62.4836" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter4_f" x="91.0208" y="765.523" width="284.096" height="117.43" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter5_f" x="8.72735" y="679.62" width="115.662" height="106.364" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter6_f" x="1421.77" y="992.323" width="470.689" height="106.419" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <filter id="filter7_f" x="1848.07" y="977.752" width="209.829" height="67.3381" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                <feGaussianBlur stdDeviation="1" result="effect1_foregroundBlur"/>
                </filter>
                <linearGradient id="paint0_linear" x1="403" y1="423.728" x2="403" y2="441.728" gradientUnits="userSpaceOnUse">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="#00182B"/>
                </linearGradient>
                <linearGradient id="paint1_linear" x1="1741" y1="411.728" x2="1741" y2="429.728" gradientUnits="userSpaceOnUse">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="#00182B"/>
                </linearGradient>
                <linearGradient id="paint2_linear" x1="1049" y1="693.556" x2="1049" y2="715.556" gradientUnits="userSpaceOnUse">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="#00182B"/>
                </linearGradient>
                <radialGradient id="paint3_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(1152.43 207.7) rotate(10.0236) scale(398.197 45.6084)">
                <stop stop-color="#0DFFD3"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint4_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(837.336 199.397) rotate(-162.033) scale(199.923 43.8233)">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint5_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(771.881 1019.16) rotate(-171.46) scale(186.796 43.5001)">
                <stop stop-color="#0DFFD3"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint6_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(909.567 994.827) rotate(23.164) scale(104.372 37.5577)">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint7_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(227.763 784.388) rotate(25.6822) scale(224.928 60.1753)">
                <stop stop-color="#0DFFD3"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint8_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(64.9814 774.431) rotate(-138.266) scale(131.828 49.5311)">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint9_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(1683.44 1079.01) rotate(174.493) scale(351.292 66.9907)">
                <stop stop-color="#0DFFD3"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                <radialGradient id="paint10_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(1936.92 985.697) rotate(7.00756) scale(187.276 60.621)">
                <stop stop-color="#005CA2"/>
                <stop offset="1" stop-color="white" stop-opacity="0.0190476"/>
                </radialGradient>
                </defs>
                </svg>
        </div>
    </div>
    <!-- HERO -->
    <section class="container hero">
        <div class="container-item">
            <div style="text-align: center;">
                <h1 style="font-size: 168px;">{% block code_error %}{% endblock %}</h1>
            </div>
            <div>
                <h3 class="mask text-center mt-1">{% block primeiro_lb %}{% endblock %}</h3>
            </div>
            <div>
                <h4 class="mask text-center mt-1">{% block segundo_lb %}{% endblock %}</h4>
            </div>
            <div class="text-center"><a href="{% url 'home:index' %}" class="arrow git">ir pro inicio</a></div>
        </div>
    </section>
</body>

</html>